import React, {useEffect, useState} from "react";
import classNames from 'classnames/bind';
import styles from './TaskListStyle.module.scss';
import TaskList from "../../../components/TaskList/TaskList";
import Search from "../../../components/Search/Search";
import DetailTaskScreen from "../DetailTask/DetailTaskScreen";
import CreateTaskScreen from "../CreateTask/CreateTaskScreen";
import QuicklyHandleTasksScreen from "../QuicklyHandleTasks/QuicklyHandleTasksScreen";

const cx = classNames.bind(styles);

const TaskListScreen = () => {

    const dataList = [
        {
            "task_id": 619,
            "tu_id": 2769,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "Về việc báo cáo tình hình thực hiện Quyết định số 749/QĐ-TTg; Quyết định số 942/QĐ-TTg năm 2023 \n",
            "progress": 0,
            "permission": 0,
            "is_pined": true,
            "priority": 0,
            "expire_date": "2023-12-20T00:00:00",
            "created_date": "2023-12-07T08:33:47",
            "date_line": "20/12/2023",
            "created_date_line": "07/12/2023",
            "complete_date": null,
            "updated_date": "2024-09-05T14:59:24",
            "updated_date_line": "05/09/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490",
            "user_id": 289,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Trương Văn Hải",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 806,
            "tu_id": 3212,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "Kiểm tra phân loại Vb đến trên app - Giao nhiệm vụ từ văn bản => test chinh sua nv - tesst",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 3,
            "expire_date": "2024-11-19T00:00:00",
            "created_date": "2024-11-19T00:00:00",
            "date_line": "19/11/2024",
            "created_date_line": "19/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-22T09:21:33",
            "updated_date_line": "22/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 815,
            "tu_id": 3236,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 1,
            "state": 2,
            "title": "tesst tao nv nang cao 1 - tesst chinh sua",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 1,
            "expire_date": "2024-08-17T00:00:00",
            "created_date": "2024-08-16T00:00:00",
            "date_line": "17/08/2024",
            "created_date_line": "16/08/2024",
            "complete_date": null,
            "updated_date": "2024-10-22T15:46:02",
            "updated_date_line": "22/10/2024",
            "total_child_task": 1,
            "total_child_task_ids": "817",
            "sort_status": 1,
            "organization": null,
            "department": "490.491",
            "user_id": 291,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Chờ duyệt",
            "label_name": "Nguyễn Thị Kim Hà",
            "list_child_task": [
                {
                    "task_id": 817,
                    "tu_id": 3244,
                    "role": 1,
                    "has_read": true,
                    "parent_id": 815,
                    "type": 0,
                    "status": 4,
                    "state": 3,
                    "title": "test tao nv con",
                    "progress": 100,
                    "permission": 0,
                    "is_pined": false,
                    "priority": 0,
                    "expire_date": "2024-08-16T00:00:00",
                    "date_line": "16/08/2024",
                    "created_date_line": "16/08/2024",
                    "updated_date_line": "22/10/2024",
                    "complete_date": null,
                    "created_date": "2024-08-16T00:00:00",
                    "total_child_task": "",
                    "total_child_task_ids": "",
                    "sort_status": 2,
                    "organization": null,
                    "department": "490.491",
                    "user_id": 291,
                    "status_name": "Đã kết thúc",
                    "label_name": "Nguyễn Thị Kim Hà",
                    "target_user_name": "Nguyễn Thị Kim Hà"
                }
            ],
            "has_sub_task": true,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 863,
            "tu_id": 3394,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 2,
            "state": 0,
            "title": "giao nhiệm vụ 1233",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-10-18T00:00:00",
            "created_date": "2024-10-17T18:15:54",
            "date_line": "18/10/2024",
            "created_date_line": "17/10/2024",
            "complete_date": null,
            "updated_date": "2024-10-17T18:58:15",
            "updated_date_line": "17/10/2024",
            "total_child_task": 1,
            "total_child_task_ids": "884",
            "sort_status": 0,
            "organization": null,
            "department": "490",
            "user_id": 291,
            "target_organization": null,
            "target_department": "490",
            "target_user_id": 291,
            "status_name": "Xin gia hạn",
            "label_name": "Nguyễn Thị Kim Hà",
            "list_child_task": [
                {
                    "task_id": 884,
                    "tu_id": 3457,
                    "role": 0,
                    "has_read": true,
                    "parent_id": 863,
                    "type": 1,
                    "status": 0,
                    "state": 0,
                    "title": "test con",
                    "progress": 0,
                    "permission": 0,
                    "is_pined": false,
                    "priority": 0,
                    "expire_date": "2024-11-13T00:00:00",
                    "date_line": "13/11/2024",
                    "created_date_line": "11/11/2024",
                    "updated_date_line": "11/11/2024",
                    "complete_date": null,
                    "created_date": "2024-11-11T04:23:13",
                    "total_child_task": "",
                    "total_child_task_ids": "",
                    "sort_status": 2,
                    "organization": null,
                    "department": "490",
                    "user_id": null,
                    "status_name": "Đang xử lý",
                    "label_name": "eGov - Beta",
                    "target_user_name": "Hệ thống Demo"
                }
            ],
            "has_sub_task": true,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 851,
            "tu_id": 3347,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 2,
            "state": 1,
            "title": "Nv",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-10-11T00:00:00",
            "created_date": "2024-10-11T09:57:52",
            "date_line": "11/10/2024",
            "created_date_line": "11/10/2024",
            "complete_date": null,
            "updated_date": "2024-10-22T11:34:38",
            "updated_date_line": "22/10/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 0,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Xin gia hạn",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 818,
            "tu_id": 3246,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 2,
            "state": 1,
            "title": "Test 1",
            "progress": 12,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-08-19T00:00:00",
            "created_date": "2024-08-19T10:14:56",
            "date_line": "19/08/2024",
            "created_date_line": "19/08/2024",
            "complete_date": null,
            "updated_date": "2024-10-25T15:40:59",
            "updated_date_line": "25/10/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 0,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Xin gia hạn",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 816,
            "tu_id": 3238,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 2,
            "state": 1,
            "title": "tesst tao nv nhanh",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-08-16T00:00:00",
            "created_date": "2024-08-16T13:32:24",
            "date_line": "16/08/2024",
            "created_date_line": "16/08/2024",
            "complete_date": null,
            "updated_date": "2024-10-22T11:42:38",
            "updated_date_line": "22/10/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 0,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Xin gia hạn",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 942,
            "tu_id": 3606,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 1,
            "state": 1,
            "title": "test dinh kem file 1",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T10:31:48",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T10:41:18",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 1,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Chờ duyệt",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 945,
            "tu_id": 3612,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 0,
            "title": "test tao nv dinh kem file tren mobile",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T16:07:12",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T16:07:12",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 944,
            "tu_id": 3610,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 1,
            "title": "tesst dinh kem file mobile",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T15:57:18",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T15:58:04",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 943,
            "tu_id": 3608,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 0,
            "title": "tesst dinh kem file",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T15:54:46",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T15:54:46",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 941,
            "tu_id": 3604,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 0,
            "title": "tesst 6",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T10:27:47",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T10:27:47",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 940,
            "tu_id": 3602,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 1,
            "title": "test 5",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T10:00:25",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T10:01:20",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 934,
            "tu_id": 3590,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 0,
            "title": "tesst 4",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T08:20:40",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T08:20:40",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 933,
            "tu_id": 3588,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 0,
            "title": "test 3",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T08:19:15",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T08:19:15",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 932,
            "tu_id": 3586,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 0,
            "title": "tesst 2",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T08:16:20",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T08:16:20",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 931,
            "tu_id": 3584,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 0,
            "title": "Test 1₁",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-20T00:00:00",
            "created_date": "2024-11-20T08:12:39",
            "date_line": "20/11/2024",
            "created_date_line": "20/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-20T08:12:39",
            "updated_date_line": "20/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 886,
            "tu_id": 3461,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": -1,
            "state": 0,
            "title": "Về việc văn bản đến test giao nv 1",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-11-30T00:00:00",
            "created_date": "2024-11-13T16:08:30",
            "date_line": "30/11/2024",
            "created_date_line": "13/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-13T23:08:53",
            "updated_date_line": "13/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490",
            "target_user_id": 291,
            "status_name": "Mới tạo",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 879,
            "tu_id": 3448,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 0,
            "title": "Tiêu đề nv",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-10-25T00:00:00",
            "created_date": "2024-10-25T00:00:00",
            "date_line": "25/10/2024",
            "created_date_line": "25/10/2024",
            "complete_date": null,
            "updated_date": "2024-10-25T09:10:14",
            "updated_date_line": "25/10/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.491",
            "user_id": 291,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Thị Kim Hà",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 859,
            "tu_id": 3378,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 0,
            "title": "Test 16:33 14/10",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-10-14T00:00:00",
            "created_date": "2024-10-14T16:33:02",
            "date_line": "14/10/2024",
            "created_date_line": "14/10/2024",
            "complete_date": null,
            "updated_date": "2024-10-14T16:33:02",
            "updated_date_line": "14/10/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.491",
            "user_id": 291,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Thị Kim Hà",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 848,
            "tu_id": 3338,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 0,
            "title": "Giao nhiệm vụ",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-10-10T00:00:00",
            "created_date": "2024-10-10T09:31:29",
            "date_line": "10/10/2024",
            "created_date_line": "10/10/2024",
            "complete_date": null,
            "updated_date": "2024-10-10T09:31:29",
            "updated_date_line": "10/10/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.491",
            "user_id": 291,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Thị Kim Hà",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 846,
            "tu_id": 3332,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 0,
            "title": "Chuẩn bị phong hop",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-10-10T00:00:00",
            "created_date": "2024-10-04T07:53:22",
            "date_line": "10/10/2024",
            "created_date_line": "04/10/2024",
            "complete_date": null,
            "updated_date": "2024-10-04T07:53:22",
            "updated_date_line": "04/10/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490",
            "user_id": 324,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Trung  Hiếu",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 820,
            "tu_id": 3250,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "Tesssttesst",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-08-21T00:00:00",
            "created_date": "2024-08-21T15:43:35",
            "date_line": "21/08/2024",
            "created_date_line": "21/08/2024",
            "complete_date": null,
            "updated_date": "2024-09-05T15:37:20",
            "updated_date_line": "05/09/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.491",
            "user_id": 616,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Văn thư Hiệp Thành",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 819,
            "tu_id": 3248,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "Tết",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-08-20T00:00:00",
            "created_date": "2024-08-20T13:16:43",
            "date_line": "20/08/2024",
            "created_date_line": "20/08/2024",
            "complete_date": null,
            "updated_date": "2024-11-18T16:27:06",
            "updated_date_line": "18/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.491",
            "user_id": 616,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Văn thư Hiệp Thành",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 814,
            "tu_id": 3230,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 0,
            "title": "test tajo nv nanh",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-08-16T00:00:00",
            "created_date": "2024-08-16T11:43:24",
            "date_line": "16/08/2024",
            "created_date_line": "16/08/2024",
            "complete_date": null,
            "updated_date": "2024-08-16T11:43:24",
            "updated_date_line": "16/08/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.501.502",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 757,
            "tu_id": 3097,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 0,
            "title": "Vggghhhhggghhhh",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-06-06T00:00:00",
            "created_date": "2024-06-06T16:12:23",
            "date_line": "06/06/2024",
            "created_date_line": "06/06/2024",
            "complete_date": null,
            "updated_date": "2024-06-06T16:12:23",
            "updated_date_line": "06/06/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.491",
            "user_id": 291,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Thị Kim Hà",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 720,
            "tu_id": 2991,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "giao mới cho Hà ",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-05-16T00:00:00",
            "created_date": "2024-05-16T08:35:46",
            "date_line": "16/05/2024",
            "created_date_line": "16/05/2024",
            "complete_date": null,
            "updated_date": "2024-05-16T15:38:47",
            "updated_date_line": "16/05/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.493",
            "user_id": 296,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Hoàng Xuân Liên",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 719,
            "tu_id": 2989,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "test",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-05-15T00:00:00",
            "created_date": "2024-05-15T20:39:17",
            "date_line": "15/05/2024",
            "created_date_line": "15/05/2024",
            "complete_date": null,
            "updated_date": "2024-05-16T15:33:36",
            "updated_date_line": "16/05/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.496",
            "user_id": 311,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Trần Thanh  Sơn",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 717,
            "tu_id": 2985,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "hhhhh",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-05-09T00:00:00",
            "created_date": "2024-05-09T21:02:14",
            "date_line": "09/05/2024",
            "created_date_line": "09/05/2024",
            "complete_date": null,
            "updated_date": "2024-05-13T10:22:49",
            "updated_date_line": "13/05/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490.491",
            "user_id": 616,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Văn thư Hiệp Thành",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 715,
            "tu_id": 2979,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "Test giao nhiệm vụ liên thông - TrungLVc 060524",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-05-31T00:00:00",
            "created_date": "2024-05-06T10:26:49",
            "date_line": "31/05/2024",
            "created_date_line": "06/05/2024",
            "complete_date": null,
            "updated_date": "2024-05-09T14:59:50",
            "updated_date_line": "09/05/2024",
            "total_child_task": 1,
            "total_child_task_ids": "716",
            "sort_status": 2,
            "organization": null,
            "department": "490",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490.491",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": true,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 708,
            "tu_id": 2963,
            "role": 1,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 3,
            "title": " Kiểm tra phân loại Vb đến trên app",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-05-10T00:00:00",
            "created_date": "2024-05-06T08:07:56",
            "date_line": "10/05/2024",
            "created_date_line": "06/05/2024",
            "complete_date": null,
            "updated_date": "2024-10-22T09:37:02",
            "updated_date_line": "22/10/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        },
        {
            "task_id": 876,
            "tu_id": 3438,
            "role": 2,
            "has_read": true,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 1,
            "title": "PHÂN CÔNG PHỤC VỤ HỘI NGHỊ  QUÁN TRIỆT, TRIỂN KHAI NGHỊ QUYẾT TRUNG ƯƠNG 10 KHOÁ XIII CỦA ĐẢNG",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": 0,
            "expire_date": "2024-10-26T00:00:00",
            "created_date": "2024-10-23T14:54:57",
            "date_line": "26/10/2024",
            "created_date_line": "23/10/2024",
            "complete_date": null,
            "updated_date": "2024-10-31T16:58:12",
            "updated_date_line": "31/10/2024",
            "total_child_task": 1,
            "total_child_task_ids": "877",
            "sort_status": 2,
            "organization": null,
            "department": "490",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490",
            "target_user_id": 324,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [
                {
                    "task_id": 877,
                    "tu_id": 3439,
                    "role": 1,
                    "has_read": true,
                    "parent_id": 876,
                    "type": 0,
                    "status": 0,
                    "state": 1,
                    "title": "Tham mưu Kế hoạch ",
                    "progress": 0,
                    "permission": 0,
                    "is_pined": false,
                    "priority": 0,
                    "expire_date": "2024-10-25T00:00:00",
                    "date_line": "25/10/2024",
                    "created_date_line": "23/10/2024",
                    "updated_date_line": "24/10/2024",
                    "complete_date": null,
                    "created_date": "2024-10-23T15:00:44",
                    "total_child_task": "",
                    "total_child_task_ids": "",
                    "sort_status": 2,
                    "organization": null,
                    "department": "490",
                    "user_id": 324,
                    "status_name": "Đang xử lý",
                    "label_name": "Nguyễn Trung  Hiếu",
                    "target_user_name": "Nguyễn Thị Kim Hà"
                }
            ],
            "has_sub_task": true,
            "target_user_name": "Nguyễn Trung  Hiếu"
        },
        {
            "task_id": 885,
            "tu_id": 3459,
            "role": 1,
            "has_read": false,
            "parent_id": null,
            "type": 0,
            "status": 0,
            "state": 0,
            "title": "Về việc văn bản đến test giao nv 1",
            "progress": 0,
            "permission": 0,
            "is_pined": false,
            "priority": -1,
            "expire_date": "0001-01-01T00:00:00",
            "created_date": "2024-11-13T08:32:44",
            "date_line": "01/01/0001",
            "created_date_line": "13/11/2024",
            "complete_date": null,
            "updated_date": "2024-11-13T15:34:33",
            "updated_date_line": "13/11/2024",
            "total_child_task": 0,
            "total_child_task_ids": null,
            "sort_status": 2,
            "organization": null,
            "department": "490",
            "user_id": 314,
            "target_organization": null,
            "target_department": "490",
            "target_user_id": 291,
            "status_name": "Đang xử lý",
            "label_name": "Nguyễn Tấn Đức",
            "list_child_task": [],
            "has_sub_task": false,
            "target_user_name": "Nguyễn Thị Kim Hà"
        }
    ]

    const listMenu = [
        {
            "menu_id": 1,
            "un_read": 0,
            "total": 54,
            'name_menu': 'Nhiệm vụ chủ trì',
        },
        {
            "menu_id": 2,
            "un_read": 0,
            "total": 50,
            'name_menu': 'Nhiệm vụ phối hợp',
        },
        {
            "menu_id": 3,
            "un_read": 0,
            "total": 1,
            'name_menu': 'Nhiệm vụ đã giao',
        },
        {
            "menu_id": 4,
            "un_read": 0,
            "total": 96,
            'name_menu': 'Nhiệm vụ theo dõi',
        },
        {
            "menu_id": 6,
            "un_read": 0,
            "total": 21,
            'name_menu': 'Nhiệm vụ kết thúc',
        }
    ]

    const [menuSelected, setMenuSelected] = useState(listMenu[0])
    const [listChose, setListChose] = useState([
        {
            idChose: 1,
            nameChose: 'Nhiệm vụ',
        },
        {
            idChose: 2,
            nameChose: 'Tìm kiếm',
        }
    ])
    const [chose, setChose] = useState(listChose[0])
    const [showModule, setShowModule] = useState(false);
    const [showModuleCreateTask, setShowModuleCreateTask] = useState(false);

    const handleDetailTask = (itemSelect) => {
        const updatedData = listChose.map((item, index) => {
            return {
                idChose: index + 1,
                nameChose: item.nameChose,
                item: item.item || {},
            }
        })
        updatedData.push({
            idChose: listChose.length + 1,
            nameChose: itemSelect.title,
            item: itemSelect,
        })
        setListChose(updatedData);
        setChose(updatedData[updatedData.length-1]);
    }

    const handleDeleteChose = (item) => {
        const updatedData = listChose.filter(chose => chose.idChose !== item.idChose);
        setListChose(updatedData);
        console.log(listChose);
        setChose({
            idChose: 1,
            nameChose: 'Nhiệm vụ',
        });
    }

    return (
        <div className={cx('TaskListScreen')}>
            <div className={cx('row')}>
                <div className={cx('col-md-2', 'list_menu')}>
                    <div className={cx('text_header_menu', 'mt-4', 'mb-4')}>Xử lý nhiệm vụ</div>

                    {listMenu.map(itemMenu => (
                        <div
                            className={cx('flex', 'align-items-center', 'mb-2', 'row_menu', (menuSelected.menu_id === itemMenu.menu_id ? 'active' : ''))}
                            onClick={() => {
                                setMenuSelected(itemMenu);
                            }}
                        >
                            <div className={cx('me-3')}>
                                <i className={cx('bx bx-folder-open', 'icon_folder', 'me-3')}></i>
                                {itemMenu.name_menu}
                            </div>
                            <div className={cx('number_total')}>
                            {itemMenu.total}
                            </div>
                        </div>
                    ))}
                </div>

                <div className={cx('col-md-2')}></div>
                <div className={cx('col-md-10', 'list_task')}>
                    <div className={cx('flex', 'row_lua_chon')}>
                        {listChose.map(itemChose => (
                            <div
                                className={cx('item_lua_chon', (chose.idChose === itemChose.idChose ? 'active_lua_chon' : ''), (itemChose.idChose !== 1 && itemChose.idChose !== 2) ? 'pl_item_lua_chon' : '')}
                                onClick={() => setChose(itemChose)}
                            >
                                {itemChose.nameChose}
                                {itemChose.idChose !== 1 && itemChose.idChose !== 2 ? (<button
                                    className={cx("btn btn-close", 'close_item_lua_chon')}
                                    onClick={() => handleDeleteChose(itemChose)}
                                ></button>) : null}
                            </div>
                        ))}
                    </div>
                    {chose.idChose === 1 ? (<TaskList tasks={dataList} handleDetailTask={handleDetailTask}/>)
                        : chose.idChose === 2 ? (<Search />)
                            : (<DetailTaskScreen task={chose} />)}
                </div>
            </div>

            {showModule && (<QuicklyHandleTasksScreen setShowModule={setShowModule} />)}

            <div
                onClick={() => setShowModuleCreateTask(!showModuleCreateTask)}
            >
                <i className={cx('bx bx-plus-circle', 'btn_create_task')}></i>
            </div>

            {showModuleCreateTask && (<CreateTaskScreen setShowModuleCreateTask={setShowModuleCreateTask} />)}
        </div>
    )
}

export default TaskListScreen;
